# Generated by Django 4.2.5 on 2023-09-20 03:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import file_upload_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(blank=True, max_length=255, null=True)),
                ('file_path', models.FileField(upload_to=file_upload_app.models.file_to_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['py'])])),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='success', max_length=15)),
                ('upload_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('update', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_new', models.BooleanField(default=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
