# Generated by Django 4.2.5 on 2023-09-20 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('file_upload_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('In progress', 'Отправлено на тесты'), ('Verified!', 'Проверка завершена'), ('Failed', 'Не удачно')], default='In progress', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('result', models.JSONField(blank=True, default=dict, null=True)),
                ('file_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_checks', to='file_upload_app.uploadedfile')),
            ],
        ),
    ]
